### ISSUE TITLE
Comment blocks should be `//` not `/* */`

### ISSUE THREAD

**Issue by bassettsj** [atom/language-sass#12]
When writing SCSS/SASS, I would expect that the comment command would use the `//` style instead of the `/* */`, I think there was a recent change in either the editor or the language bundle to change the style of comments and it is driving me nuts, almost to the point of using another editor for when I write SCSS on projects. There is a big difference in how they treat the normal CSS style comments which are still compiled, and the `//` comments.

``` scss
/* .button{
  color: red;
  &:hover,
  &:focus{
    color: darken(red, 10%);
  }
} */
```

becomes

``` css
/* .button{
  color: red;
  &:hover,
  &:focus{
    color: darken(red, 10%);
  }
} */
```

while 

``` scss
//.button{
//  color: red;
//  &:hover,
//  &:focus{
//    color: darken(red, 10%);
//  }
```

becomes 

``` css
```
