### ISSUE TITLE
Unicode codes improperly highlighted

### ISSUE THREAD

**Issue by adambuczynski** [atom/language-sass#150]
Compare CSS:

![image](https://cloud.githubusercontent.com/assets/490562/16669052/a78eeeda-44e7-11e6-8d1d-f881663b6163.png)

And SASS:

![image](https://cloud.githubusercontent.com/assets/490562/16669062/b0135ee2-44e7-11e6-8b6e-5fbf1989dc29.png)

Code:

```scss
.icon-bag:before {
    content: "\e54c";
}
.icon-categories:before {
    content: "\e1bd";
}
```

Seems like the last part of the character is missing a `constant.character.escape.css` class. Maybe the fix for this issue can be ported from language-css, as it seems to be doing it right.
