### ISSUE TITLE
SCSS highlighter loses track with & and string interpolation

### ISSUE THREAD

**Issue by aeschli** [atom/language-sass#185]
_From @prencher on November 8, 2016 23:57_

- VSCode Version: 1.7.1
- OS Version: Windows 10

The following does not highlight correctly:
```scss
.test {
    &--foo { color: white; }
    &#{&}--bar { color: black; }
    &some-#{$placeholder} { color: green; }
}
```

![example](https://cloud.githubusercontent.com/assets/138147/20122361/f9eaab70-a5cb-11e6-9ecf-a660384d33b4.png)

Expected would be for the entire selector to remain green, and if possible, have the interpolation highlighted individually.

I've tested with all bundled themes, and they are all wrong in slightly different ways, so I assume the problem lies with the language provider.

_Copied from original issue: Microsoft/vscode#15219_
