### ISSUE TITLE
Selectors with escaped special characters highlight incorrectly

### ISSUE THREAD

**Issue by albell** [atom/language-sass#187]
![screen shot 2016-11-21 at 11 02 23 am](https://cloud.githubusercontent.com/assets/1142025/20496642/e3d38e24-afda-11e6-97bc-ed30b5ae6224.png)

![screen shot 2016-11-21 at 11 09 16 am](https://cloud.githubusercontent.com/assets/1142025/20496674/fb697aa8-afda-11e6-8dd8-937c94d49f49.png)

The immediate use case is class libraries that use the @ symbol to target certain breakpoints. It should work regardless, though.

**Comment by 50Wliu** [comment]
```scss
.parent-selector {
  font-size: 10px;

  .legit-class-name\@sm {
    font-size: 20px;
  }
}
```
