### ISSUE TITLE
SCSS keywords highlighted incorrectly

### ISSUE THREAD

**Issue by SitanHuang** [atom/language-sass#204]
### Description

SCSS key word initial and pre-wrap is colored gray instead of white colored like inherit or normal.

### Steps to Reproduce

1. create SCSS

2. put
```css
.circle {
        left: 0;
        right: 15px;
        left: initial;
      }

      p {
        margin-top: 0;
        margin-left: 15px;
        margin-right: 0;
        white-space: pre-wrap;
      }
```

3. pre-wrap and initial are not colored as white, `wrap` is colored white but `pre` is colored grey

**Expected behavior:**
initial and pre-wrap all colored as white

**Actual behavior:** [What actually happens]
pre-wrap and initial are not colored as white, `wrap` is colored white but `pre` is colored grey

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
```
Atom    : 1.15.0-beta2
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

Thank you!
