### ISSUE TITLE
Incorrect syntax highlighting with selector interpolation and underscores

### ISSUE THREAD

**Issue by aar0nr** [atom/language-sass#208]
### Description

<img width="183" alt="scss_bug2" src="https://cloud.githubusercontent.com/assets/173250/25447567/e9731648-2a72-11e7-9d03-c4fe74f65654.png">

**Expected behavior:** I expect the ```__foo``` portion of the selector to be the same color as other selectors.

**Actual behavior:** The selector is colored incorrectly.

#### Atom

Atom: 1.16.0
Electron: 1.3.13
Chrome: 52.0.2743.82
Node: 6.5.0

#### APM

apm: 1.16.1
npm: 3.10.5
node: 6.9.5 x64
python: 2.7.13
git: 2.12.2

**Comment by 50Wliu** [comment]
```scss
.test {
  #{&}__foo {
    padding: 10px;
  }

  #{&}--foo {
    padding: 10px;
  }
}
```
