### ISSUE TITLE
:not operator breaking following highlights

### ISSUE THREAD

**Issue by danqing** [atom/language-sass#228]
<img width="389" alt="screen shot 2017-07-20 at 12 52 42 pm" src="https://user-images.githubusercontent.com/5134133/28436061-8090c5ec-6d4a-11e7-9496-211200b2ae40.png">

GitHub does it right:

```scss
.popover-target {
  &:not(.popover-open) .popover-wrapper {
    opacity: 0;
    pointer-events: none;
  }
}
```
