### ISSUE TITLE
'$=' in attribute selector is highlighted as invalid

### ISSUE THREAD

**Issue by aeschli** [atom/language-sass#231]
_From @nbar1 on June 9, 2017 16:29_

1. Open a SCSS file with the following content:
```
div[id$="divPAGEBAR"] {
	color: transparent;
	padding-right: 10px;
}
```
2. See that syntax highlighting is incorrect vs. using a CSS filetype: the '$' gets the scope `invalid.illegal.scss`. `$=` is a valid operator in a [attribute selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors).
3. This is a new issue introduced with a recent update

<img width="232" alt="screen shot 2017-06-09 at 3 36 41 pm" src="https://user-images.githubusercontent.com/622363/26991718-8496dc6c-4d29-11e7-9bef-6a374108957b.png">

_Copied from original issue: Microsoft/vscode#28366_

**Comment by aeschli** [comment]
_From @FynnZW on June 12, 2017 12:51_

Can confirm - additionally, certain selectors are getting a different color:
```scss
    a::after {
        display: block;
        height: 100%;
        width: 100%;
        // content and cursor have selector color  (would be green in this example)
        content: "";
        cursor: pointer;
    }
```
This happens even with all extensions disabled.

OSX Sierra
VSCode Version 1.13.0 (1.13.0)
