### ISSUE TITLE
SCSS:  Tags nested inside rules are not styled as tags

### ISSUE THREAD

**Issue by aeschli** [atom/language-sass#237]
0.61.2 

Steps to Reproduce:

1.  Using code such as

````scss
.showcase-modal_overview_header {
  display: flex;
  justify-content: space-between;
  align-items: flex-end;
  margin-bottom: 12px;
  h3 {
    margin: 0 0 -7px;
  }
}
````
2. The `h3` is not colored as a tag:

<img width="341" alt="screen shot 2017-10-25 at 2 12 52 pm" src="https://user-images.githubusercontent.com/835148/32015286-a125be12-b98e-11e7-9647-59ede2a6d0e7.png">

This is a regression.

_Copied from original issue: Microsoft/vscode#36923_
