### ISSUE TITLE
Pseudo-classes are no longer correctly scoped

### ISSUE THREAD

**Issue by smlombardi** [atom/language-sass#239]
In VSCode insiders, in a nested item like this:

````scss
.dropdown-item {
  padding: 10px 30px 5px 20px;
  color: $gray-500;
  white-space: nowrap;
  font-family: $font-family-sans-serif;

  &:hover {
    background-color: $gray-60;
  }

  &:active, &.active {
    background-color: $gray-60;
    color: $gray-500;
  }

  &:last-child {
    padding-bottom: 10px;
  }

  &.disabled {
    color: $gray-300;
  }
}
````

The `&:hover` is not correctly colored:

<img width="438" alt="screen shot 2017-10-30 at 10 02 01 am" src="https://user-images.githubusercontent.com/835148/32174847-6643cdce-bd59-11e7-9c59-b37aca6cb7dc.png">

the `:active` **is** correctly colored

This is a regression, it used to work fine..
