### ISSUE TITLE
Wrong syntax highlighting for property following nested properties

### ISSUE THREAD

**Issue by aeschli** [atom/language-sass#250]
_From @ramya-rao-a on March 27, 2018 18:57_

- VSCode Version: 1.21
- OS Version: Any

Steps to Reproduce:

1. Have the below content in a scss file. Observe the last property is in white

![image](https://user-images.githubusercontent.com/16890566/37988531-fd376f8a-31b5-11e8-9f87-751b06539cec.png)

_Copied from original issue: Microsoft/vscode#46753_

**Comment by aeschli** [comment]
@ramya-rao-a Please always paste the sample code to speed up the investigations.
```
/* nested properties */
.funky {
  font: 2px/3px {
    family: fantasy;
    size: 30em;
    weight: bold;
  }
  color: black;
}
```

**Comment by burtek** [comment]
Same here.

![image](https://user-images.githubusercontent.com/2940958/65032608-c3a64200-d943-11e9-93cc-99f6bd4f082e.png)
![image](https://user-images.githubusercontent.com/2940958/65032612-c5700580-d943-11e9-8043-3021643a44a1.png)

GitHub syntax highlighting is also affected:

```scss
.button {
    @include fontDemi;

    border: 0 {
        radius: 30px;
    };
    background-color: $buttonColor;
}
```

```scss
.button {
    @include fontDemi;

    border: {
        radius: 30px;
    };
    background-color: $buttonColor;
}
```


Taken from: https://github.com/microsoft/vscode/issues/81038
