### ISSUE TITLE
Root-level @at-root selector in SCSS partial causes false syntax errors

### ISSUE THREAD

**Issue by alexr00** [atom/language-sass#265]
_From @briman0094 on January 3, 2019 15:54_

When placing an `@at-root` directive at the root-level of a SCSS file, Visual Studio Code's tokenizer seems to break completely, highlighting the `@at-root` and most other SCSS features in the proceeding block as syntax errors. Normally the `@at-root` selector would be useless at the root-level, but in a partial file which is included inside a selector from another file, it makes sense and is valid SCSS.

Reproduction files:

test.scss
```scss
$a-variable: 4px;

#main {
    @import "testpartial";
}

#main2 {
    background-color: red;
}
```

_testpartial.scss
```scss
.some-class {
    color: red;
}

@at-root #main2 .some-class {
    color: blue;
    padding-left: calc( #{$a-variable} + 8px );
}
```

Resulting CSS from `node-sass test.scss` (correct output):

```css
#main .some-class {
  color: red; }

#main2 .some-class {
  color: blue;
  padding-left: calc( 4px + 8px); }

#main2 {
  background-color: red; }
```

Screenshot of the false errors in Code:
![image](https://user-images.githubusercontent.com/816612/50647099-62694a80-0f3d-11e9-90a4-77e5635801a2.png)

_Copied from original issue: Microsoft/vscode#65976_
