### ISSUE TITLE
Support for New @use and @forward syntax

### ISSUE THREAD

**Issue by sarsamurmu** [atom/language-sass#270]
## Summary

Sass had now released new module system and it comes with new keywords like @use and @forward. So it changes the syntax completely.

## Motivation

For the new syntax, it marks a few things wrong like
```scss
@use "variables";
@use "strings";

#{string.$prefix}-class {
  color: variables.$brandBlue;
}
```
Here `$` in marked as wrong and `@use` aren't highlighted.

**Comment by sarsamurmu** [comment]
For reference here are all new syntax which isn't highlighted properly
```scss
@use "file";
@use "file" as f;
@forward "file";
@forward "styles" show addShadow;
@forward "newStyles" hide removeColor;
@forward "strings" as str-*;
@use "colors" as clr;
@use "functions" as funs;
@use "breakpoints";

#{strings.$prefix}-btn {
  background-color: clr.$green;
  color: funs.getColorForBg(clr.$green);

  @include breakpoints.mobile {
    font-size: 18px;
  }
}
```
