### ISSUE TITLE
translate3d(0, 0, 0) is assumed an RGB value

### ISSUE THREAD

**Issue by thomaslindstrom** [atom/language-sass#7]
``` scss
    div {
         -webkit-transform: translate3d(0, 0, 0);
    }
```

`0, 0, 0` is given the class name `constant other color rgb-value scss`
