### ISSUE TITLE
Using brackets inside selector breaks theme?

### ISSUE THREAD

**Issue by JimmyMultani** [atom/language-sass#79]
I've noticed that using brackets inside a class/id will break the theming of code after.

![screenclip](https://cloud.githubusercontent.com/assets/1281284/9744152/14a6688a-5638-11e5-931a-55ef9b556a4f.png)

I am on Atom 1.0.11 as of this posting. I switched back to the One Dark UI and theme, but that did not fix the issue. Removing all plugins did not fix it either.

I am at a loss as to what to do next. Any idea why this is happening?

Thanks.

**Comment by JimmyMultani** [comment]
Hey @50Wliu, if there is anything else that you need, please let me know. Thanks.

**Comment by 50Wliu** [comment]
@JimmyMultani I'll try to look at this soon, but no guarantees.

**Comment by simurai** [comment]
I can reproduce it when using `.scss`:

```scss
.test {
  top: 50%;
  .nested {
    background: red;
  }
  bottom: 50%;
}
```

![screen shot 2015-10-09 at 10 44 17 am](https://cloud.githubusercontent.com/assets/378023/10384189/0fc5ce7a-6e73-11e5-8f4c-d28a8d390abd.png)

**Comment by bjmiller** [comment]
FWIW, this also breaks detection of the last bracket as having scope `punctuation.section.property-list.end.scss`

**Comment by danieldiekmeier** [comment]
I also have this problem, and a fix would be greatly appreciated.

```
.Order {
  padding: 1rem;

  background: {
    color: #fff;
  }

  box-shadow: 2px 0 3px rgba(#000, 0.2);
}
```

![screen shot 2016-01-15 at 01 12 47](https://cloud.githubusercontent.com/assets/2098462/12341872/1d8b0012-bb25-11e5-8a5b-5fa58a62b7b8.png)

**Comment by electerious** [comment]
Seems to happen for everything after a nested selector:

```scss
// Works fine
.a {
  width: 100%; // <= Highlighted
  &__b {
    width: 100px;
  }
}
```

```scss
// Doesn't work
.a {
  &__b {
    width: 100px;
  }
  width: 100%; // <= Not highlighted
}
```

```scss
// Doesn't work either
.a {
  width: 100%; // <= Highlighted
  &__b {
    width: 100px;
  }
  width: 100%; // <= Not highlighted
}
```
