### ISSUE TITLE
Relative protocol highlights as if it were commented out

### ISSUE THREAD

**Issue by ccheney** [atom/language-sass#82]
```css
.brand {
    background: transparent url(//placehold.it/350x500) 0 0 / cover no-repeat;
}
```

It renders completely fine in the output css it just appears to be commented in the editor.

![screen shot 2015-10-22 at 4 21 01 pm](https://cloud.githubusercontent.com/assets/302437/10678598/09c77238-78d9-11e5-818c-d29d96816a65.png)

![screen shot 2015-10-22 at 4 22 30 pm](https://cloud.githubusercontent.com/assets/302437/10678612/21daa9a8-78d9-11e5-95a4-9eda1ef6d153.png)

Perhaps there's a way to detect if // is within url() and disable the comment highlighting?
